var moment = require('moment');

module.exports = (sequelize, type) => {
    var preset = sequelize.define('preset', {
        package_id: {
            type: type.INTEGER,
            primaryKey: true
        },
        title: type.STRING,
        package_code: type.INTEGER,
        package_name: type.STRING,
        nationality: type.INTEGER,
        destination: type.STRING,
        city_id: type.INTEGER,
        category: type.INTEGER,
        package_stock: type.INTEGER,
        package_remaining_stock: type.INTEGER,
        days: type.INTEGER,
        start_date: type.DATE,
        end_date: type.DATE,
        min_adult: type.INTEGER,
        max_adult: type.INTEGER,
        min_child: type.INTEGER,
        max_child: type.INTEGER,
        infant: type.INTEGER,
        currency: type.STRING,
        adult_start_price: type.STRING,
        child_start_price: type.STRING,
        child_infant_price: type.STRING,
        tour_include: type.STRING,
        terms_and_conditions: type.STRING,
        child_policy: type.STRING,
        cancellation_policy: type.STRING,
        created_at: type.DATE,
        updated_at: type.DATE,
        thumbnail_image: type.INTEGER,
        main_image: type.INTEGER,
        other_image: type.INTEGER,
        status: type.INTEGER,
        user_id: type.INTEGER,
        package_details: type.STRING,
        tour_highlights: type.STRING,
        days_itinerary: type.STRING,
        tour_exclude: type.STRING,
        start_sale_date: type.DATE,
        end_sale_date: type.DATE,
        is_free_sale: type.INTEGER,
        is_deleted: type.INTEGER,
        region: type.INTEGER,
        perma_link: type.INTEGER,
        locale: type.INTEGER,
        video_url: type.STRING,
        has_visa: type.INTEGER,
        has_dinings: type.INTEGER,
        has_wellness: type.INTEGER,
        has_holiday: type.INTEGER,
        has_cruises: type.INTEGER,
        has_marhaba: type.INTEGER,
        has_transfers: type.INTEGER,
        has_insurance: type.INTEGER,
        has_car: type.INTEGER,
        has_activities: type.INTEGER,
        has_flight: type.INTEGER,
        has_hotel: type.INTEGER,
        rejected_reason: type.STRING,
        package_status: {
            type: type.ENUM,
            values: ['pending', 'approved', 'rejected', 'draft']
        },
        flight_from: type.INTEGER,
        flight_to: type.INTEGER,
        package_days: type.STRING,
        package_price: type.STRING,
        package_featured: type.INTEGER,
        notes: type.STRING,
    }, {
            freezeTableName: true,
            // subQuery: false,
            timestamps: false,
            // underscored: true,
        });
    preset.removeAttribute('id');
    return preset;
};
