export interface CreateNewProfile {
    salutation: String,
    first_name: String,
    status:Number,
    last_name: String,
    a_dob: Date,
    gender: String,
    passengerType: String,
    companyName: String,
    marital_status: String,
    nationality: String,
    address: String,
    dob: Date,
    list_country: String,
    postal_code: String,
    state: String,
    city: String,
    street: String,
    mobile_number: String,
    emergency_contact: String,
    email_address1: String,
    email_address2: String,
    relationship: String,
    associate_profile: String,
    document1: String,
    document2: String,
    document3: String,
    document_number1: String,
    image1:String,
    document_number2: String,
    image2: String,
    document_number3: String,
    image3: String,
    a_issueDate: Date,
    a_expiryDate: Date,
    b_issueDate: Date,
    b_expiryDate: Date,
    c_issueDate: Date,
    c_expiryDate: Date,
    a_placeofissue: String,
    b_placeofissue: String,
    c_placeofissue:String,
    passenger_type: String,
    company_name: String,
    designation: String,
    traveller_type: String,
    company_emailid: String,
    traveller_remarks: String,
    other_remarks: String,
    company_address: String,
    employeeId: String,
    department: String,
    company_number: String,
    cabin_class: String,
    meal_type: String,
    meal_type2: String,
    classification: String,
    airline_details:String,
    corporate: String,
}