export interface NewAgencyProfile {
    agency_profile_id: number,
    organisation_id: number,
    responsible_office: string,
    department_contact_name: string,
    agent_contact_name: string,
    number: {},
    email: {},
    address: {},
    bank_accounts: {},
    direct_debit_authorized: boolean,
    forms_of_payment: {},
    fare_price_override: {},
    endorsements: {},
    discounts: number,
    commissions: {},
    accounting: {},
    remarks: {},
    profile_notes: {},
    priority_lines1: {},
    priority_lines2: {},
    follow_up: {},
}