export interface NewGroupProfile {
    group_profile_id: number,
    organisation_id: number,
    group_name: string,
    group_description: string,
    group_index: string,
    languages: string,
    number: {},
    email: {},
    address: {},
    responsible_office: string,
    department_contact_name: string,
    agent_contact_name: string,
    member1: boolean,
    group_members: {},
    remarks: {},
    profile_notes: {},
    priority_lines1: {},
    priority_lines2: {},
    follow_up: {},
}