export interface ActivitySearchLog {
    activities_search_logs_id:number,
    user_id:number,
    agent_code:string,
    organisation_id:number,
    browserIp:string,
    browserAgent:string,
    startDate:Date,
    endDate:Date,
    trip:string,
    adultCount:number,
    childCount:number,
    childAges:number,
    country:string,
    currency:string,
    responseKey:{},
    created_at:Date,  
}