export interface PointOfSale {
    organisation_id: {
        type: Number,
        primaryKey: true
    },
    contact_person_email: String,
    parent_id: Number,
    agent_code: Number,
    name: String,
    agent: String,
    api_key: String,
    secret_key: String,
    email: String,
    contact: String,
    country_id: Number,
    currency_id: Number,
    corporate_type: String,
    identification_id: Number,
    contact_mobile_number: String,
    contact_person_name: String,
    timezone_id: Number,
    is_shareable: Number,
    is_supervision: Number,
    schema: Number,
    address_1: String,
    address_2: String,
    city_id: Number,
    state_province: String,
    zip: String,
    image_file4: String,
    image_file3: String,
    image_file2: String,
    image_file1: String,
    contact_country_id: Number,
    associated_sales_person: String,
    credit_limit: Number,
    business_id: String,
    associated_office: String,
    associated_category: Number,
    branch: String,
    member_of: String,
    member_number: String,
    bookings_month: String,
    revenue_month: String,
    image_website: String,
    image_invoice: String,
    image_email: String,
    terms_conditions: String,
    organisation_stats: String,
    is_active: Number,
    status: Number,
    active_suppliers: String,
    domestic_city: String,
    approval_levels: String,
    approval_managers: String,
    numberOfUsers: Number,
    payment_gateway: Number,
    fax_no: String,
    domain_url: String,
    organisation_theme: String,
    theme_settings: String,
    back_office_id: String,
    // back_office_name:
    // {
    //     type: type.ENUM,
    //     values: ['calico'],
    // },
    queue_service: String,
    created: String,
    hierarchy_id: String,
    // created: {
    //     type: type.DATE,
    //     get() {
    //         return moment(this.getDataValue('created')).format('DD/MM/YYYY h:mm:ss');
    //     },
    // }
}