export interface Registration {
    registration_id: {
        type: Number,
        primaryKey: true
    },
    iata_status: Number,
    company_name: String,
    company_reg_no: String,
    iata_number: String,
    zip_code: String,
    company_address: String,
    company_mobile: String,
    company_phone: String,
    nature_of_business: String,
    country_id: String,
    city_id: String,
    currency_id: String,
    time_zone: String,
    website: String,
    logo: String,
    show_code: String,
    first_name: String,
    last_name: String,
    customer_email: String,
    designation: String,
    username: String,
    password: String,
    contact_accounts_name: String,
    contact_operations_name: String,
    contact_managment_name: String,
    contact_accounts_email: String,
    contact_operations_email: String,
    contact_managment_email: String,
    contact_accounts_phone: String,
    contact_operations_phone: String,
    contact_managment_phone: String,
    is_delete: Boolean
}