export interface Topup {
    topup_id: {
        type: Number,
        primary: true
    },
    organization_id: String,
    agency_iata_num: String,
    agency_name: Number,
    agency_country: String,
    agency_currency: String,
    topup_type: String,
    topup_subtype: String,
    topup_purpose: String,
    document_ref_no: String,
    pnr: String,
    request_no: String,
    request_initiator: String,
    bank_name: String,
    bank_account_no: String,
    payment_date: String,
    payment_currency: String,
    payment_amount: String,
    payment_type: String,
    attachment: String,
    user_id: Number,
    bank_charge: String,
    bank_charge_currency: String,
    payment_details: String,
    currency_details: String,
    supplier_details: String,
    created_date: Date,
    topup_status: String,
    status: Number
}