var moment = require('moment');

module.exports = (sequelize, type) => {
    var staffProfile = sequelize.define('staff_profile', {
        staff_id: {
            type: type.INTEGER,
            primaryKey: true
        },
        users_id: type.INTEGER,
        designation: type.STRING,
        reporting_to: type.STRING,
        annual_budget_amount: type.FLOAT,
        business_budget_amount: type.FLOAT,
        personal_budget_amount: type.FLOAT,
        cfo_finance: type.STRING,
        cost_center: type.STRING,
        email_id: type.STRING,
        hierarchy_level: type.INTEGER,
        travel_group: type.STRING,
        contact_details: type.STRING,
        travel_arrange_person: type.INTEGER,
        passport_number: type.STRING,
        issue_date: type.DATE,
        expiry_date: type.DATE,
        passport_copy: type.STRING,
        travel_type: type.STRING,
        business_budget_cnt: type.INTEGER,
        annual_budget_cnt: type.INTEGER,
        daily_budget: type.INTEGER,
        trip_category: type.STRING,
        has_flight: type.STRING,
        has_hotel: type.STRING,
        has_caR: type.STRING,
        has_transfers: type.STRING,
        has_marhaba: type.STRING,
        has_leisure: type.STRING,
        ancillaries: type.STRING,
        conference_facilities: type.STRING,
        fq_traveler_airline: type.STRING,
        fq_traveler_hotel: type.STRING,
        fq_traveler_caR: type.STRING,
        fq_traveler_otheR: type.STRING,
        preferences: type.STRING,
        user_ip: type.STRING,
        branch: type.STRING,
        dob: type.DATE,
        hold_pnR: type.INTEGER,
        user_level: type.STRING,
        passport_country: type.INTEGER,
        family: type.STRING,
        profile_pic: type.STRING,
        employee_id: type.STRING,
        user_balance: type.STRING,
        has_balance: type.INTEGER,
        mobile_additional: type.STRING,
        dk_numbeR: type.STRING,
        service_charge: type.FLOAT,
        calculation_type: type.STRING,
        client_name: type.STRING,
    }, {
            freezeTableName: true,
            // subQuery: false,
            timestamps: false,
            // underscored: true,
        });
    staffProfile.removeAttribute('id');
    return staffProfile;
};
