const Joi = require('joi');
 
const orgSchema = Joi.object().keys({ 
         name: Joi.string().alphanum().min(3).max(30).required(),
        email: Joi.string().min(3).max(30).required(),
        contact: Joi.number().allow(null).optional(),
        country_id: Joi.string().allow("").optional(),
        currency_id: Joi.string().allow("").optional(),
        corporate_type: Joi.string().allow("").optional(),
        timezone_id: Joi.string().allow("").optional(),
        contact_mobile_number: Joi.number(),
        contact_person_name: Joi.string(),
        numberOfUsers: Joi.string().optional(),
        contact_person_email: Joi.string().allow("").min(3).max(30).optional(),
        city_id: Joi.string().allow("").optional(),
        address_1: Joi.string().allow("").optional(),
        address_2: Joi.string().allow("").optional(),
        state_province: Joi.string().allow("").optional(),
        zip: Joi.string().allow("").optional(),
        image_file4: Joi.string().allow("").optional(),
        image_file3: Joi.string().allow("").optional(),
        image_file2: Joi.string().allow("").optional(),
        image_file1: Joi.string().allow("").optional(),
        contact_country_id: Joi.string().allow("").optional(),
        associated_sales_person: Joi.string().allow("").optional(),
        credit_limit: Joi.number().optional(),
        business_id: Joi.string().required().allow("").optional(),
        associated_office: Joi.string().allow("").optional(),
        associated_category: Joi.number(),
        branch: Joi.string().allow("").optional(),
        member_of: Joi.string().allow("").optional(),
        member_number: Joi.string().allow("").optional(),
        bookings_month: Joi.string().allow("").optional(),
        revenue_month: Joi.string().allow("").optional(),
        image_website: Joi.string().allow("").optional(),
        image_invoice: Joi.string().allow("").optional(),
        image_email: Joi.string().allow("").optional(),
        terms_conditions: Joi.string().allow("").optional(),
        organisation_stats: Joi.string().allow("").optional(),
        created: Joi.string().required(),
        active_suppliers:  Joi.string().allow("").optional(),
        payment_gateway: Joi.string().allow("").optional(),
        queue_service: Joi.string().allow("").optional(),
        pos_rbd: Joi.string().allow("").optional(),
        pos_negofares: Joi.string().allow("").optional(),
        amex_card: Joi.string().allow("").optional(),
        domestictTaxCode: Joi.string().allow("").optional(),
        domestictTaxPercentage: Joi.string().allow("").optional(),
        domestictTaxCurrency: Joi.string().allow("").optional(),
        domestictTaxAirport: Joi.string().allow("").optional(),
        internationalTaxPercentage: Joi.string().allow("").optional(),
        nonAirlineTax: Joi.string().allow("").optional(),
        iata_no: Joi.string().allow("").optional(),
        monthlyTarget: Joi.string().allow("").optional(),
        domain_url: Joi.string().allow("").optional(),
    });
module.exports = orgSchema;