export interface GroupSeasonality {
    sale_id: number,
    organisation_id: number,
    users_id: number,
    shopping_code: number,
    name: string,
    created_by_organisation: number,
    is_active: number,
    is_hotel: number,
    is_flight: number,
    is_holidays: number,
    is_activities: number,
    is_car: number,
    is_transfers: number,
    is_cruises: number,
    is_visa: number,
    is_insurance: number,
    status: number,
    created: Date,
    start_date: Date,
    end_date: Date,
    is_stop_sale: number,
    is_free_sale: number,
    preference: number,
    is_all_agent: number
}

